### ISSUE TITLE
Twitter API

### ISSUE THREAD

**Issue by hbennett766** [uchicago-mobi/2016-Spring-Forum#103]
Does anyone have experience getting authentication to query the Twitter API? I can't figure out how to get authentication from the documentation that Twitter provides, and my query keeps returning a bad authentication error. I've registered my app with Twitter, and I can see all sorts of tokens, but they don't tell me how to actually use them to get API access.

**Comment by tabinks** [comment]
You should look at Fabric.io.  They are owned by Twitter and they a library to handle Twitter auth.  They might have better examples.
