### ISSUE TITLE
Updates to Firebase

### ISSUE THREAD

**Issue by nickpann** [uchicago-mobi/2016-Spring-Forum#105]
For those interested, Firebase launched several new features at Google IO. Some of them are pretty compelling and the company seems committed to supporting iOS. Rundown [here](https://firebase.googleblog.com/2016/05/firebase-expands-to-become-unified-app-platform.html).

> Hi Firebasers, Today at Google I/O we announced the largest expansion to Firebase since our initial launch four years ago. You can read the details in our blog post and on our new website. 
> 
> We added new features to help you build apps faster, including a solution for storing files and a remote configuration tool to help you customize your apps in the field. We also integrated Google Cloud Messaging into Firebase and renamed it Firebase Cloud Messaging. Our core authentication, database, and hosting services have seen big updates as well.
> 
> But we didn’t stop there. We expanded Firebase to support you throughout the entire lifecycle of your applications. We introduced Firebase Analytics, a free and unlimited analytics solution to help you learn more about your users and understand how they’re finding you. We also launched Test Lab and Crash Reporting so you can improve the quality of your apps in the field, and we announced five features to help you grow your user base: Notifications, Invites, Dynamic Links, App Indexing, and an integration with Google AdWords.
> 
> Finally, we launched a brand new admin console, and we simplified our pricing model, including adding free custom domain support for Hosting to all of our plans.

**Comment by tabinks** [comment]
Looks like they have a pretty complete offering now.  There still is the low 100 connected user limit on the free tier.  I would have thought this would have been bumped up.

**Comment by tabinks** [comment]
Also, no local storage....CoreData lives on!

**Comment by msylvester** [comment]
Firebase bringing the heat.  

Pun intended
