### ISSUE TITLE
iPhone support and submission to the app store

### ISSUE THREAD

**Issue by msylvester** [uchicago-mobi/2016-Spring-Forum#107]
I am looking to submit to the app store, but i don't want to support iphone5.  

Is it possible to submit without supporting these phones?

**Comment by susanstevens** [comment]
It's been a while since I've submitted to the app store, but I don't think you can exclude specific iPhones like that.  Are you having trouble getting auto-layout to work?  Or is there another reason you don't want to include iPhone 5?

**Comment by msylvester** [comment]
auto-layout probs

**Comment by susanstevens** [comment]
I'm happy to look at the issue at office hours today if you'd like.

**Comment by tabinks** [comment]
There is no official way to restrict by device.  There are some sneaky ways to do this by requiring frameworks that aren't supported on older devices.  The iPhone 5 doesn't support TouchID, so if you app supported TouchID then it would not be supported on iPhone 5.  This would be enforced by the app store not allowing the app to be downloaded an a device.

Personally, I would just fix the auto layout issues.  You will need to support that screen size for the iPhone 6se anyway (same screen size as the 5).
