### ISSUE TITLE
Assignment 4 Repo

### ISSUE THREAD

**Issue by tabinks** [uchicago-mobi/2016-Spring-Forum#109]
Repo: https://classroom.github.com/assignment-invitations/af652c4b607ab537fcd7f435b3fffcd3

This assignment is only for non-graduating students.  The game does not need to be complex or support multiple levels, achievements, etc. The game should showcase an introductory level knowledge of `SpriteKit`. As a reference, a flappy bird clone would be an appropriate level of work for this assignment.

If you are planning on submitting a game using `SpriteKit` for your final project, please see me to discuss the scope of this assignment.

**Comment by hbennett766** [comment]
Hey, I grabbed the repo, but it's public. Can you set it to private or resend?

**Comment by tabinks** [comment]
I just switched to private.  Human error.

**Comment by hbennett766** [comment]
Thanks!
