### ISSUE TITLE
Saving UIColor

### ISSUE THREAD

**Issue by aaizuss** [uchicago-mobi/2016-Spring-Forum#110]
For my final project, I want to save the color info for gradients. If that's all I'm saving, is it okay to save in NSUserDefaults? It seems like overkill to use CoreData just to store color values. On the other hand, I know it's bad practice to save a lot of info in NSUserDefaults and it could end up being lots of colors. What do you think? What type should the attribute be? 

StackOverflow suggests converting to NSData using NSKeyedArchiver (and using the attribute type Transformable).

**Comment by susanstevens** [comment]
Personally, I'd probably start by using `NSKeyedArchiver` and writing to the documents directory.  It doesn't sound like you're storing complex relationships between objects or doing complicated queries, so Core Data might not be necessary.  On the other hand, you're already pretty familiar with Core Data, so using it to store colors wouldn't be so bad.

**Comment by tabinks** [comment]
Also, you could just store them as RGB values in an array.  You could transform them to/from colors using UIColor(withRed:Blue:Green).  You would just read/write this as a plist, although it would only save a couple of lines as opposed to actually saving the color with `NSKeyedArchiver`.

**Comment by aaizuss** [comment]
@tabinks what do you mean "You should just read/write this as a plist?" And it definitely makes sense to store them as RGB values in an array, but where should I save? The documents directory, like Susan said?
