### ISSUE TITLE
Final Project Requirements

### ISSUE THREAD

**Issue by nickpann** [uchicago-mobi/2016-Spring-Forum#122]
It was mentioned in class on Saturday that there were some final project requirements, but I can't find where they are enumerated.

Could someone point me to those, or are they more or less the same as last quarter? Thanks.

**Comment by susanstevens** [comment]
[Here](https://ff8276a3d76177159b643022d4cc86d3f633fc86.googledrive.com/host/0B3XzcKIiWyccdlgtOW42N0xQZjQ/MPCS51032/2016-Spring/2016-Spring-FinalProjectRequirements.pdf)!  There's also a link to it under the Session 9 Notes on the class website.

**Comment by nickpann** [comment]
Thanks
