### ISSUE TITLE
No Back Button on Navigation Controller

### ISSUE THREAD

**Issue by aaizuss** [uchicago-mobi/2016-Spring-Forum#123]
I had this problem before, and @tabinks said it was a weird Xcode bug but I don't remember how to fix it. 

I have a regular ViewController with a button that segues to a table view controller. The table view controller is embedded in a navigation controller. I use a storyboard "show" segue between the view controller and the table view controller, but no back button appears in the navigation bar. I've tried deleting the table view controller and adding it back again, and the same thing happens.

**Comment by tabinks** [comment]
To fix the bug, you need to embed the view controller in a navigation controller before hooking it up. 
- Drag out the second view controller
- Select "Embed in Navigation Controller" from the "Editor" menu bar
- Delete the newly created navigation controller
- Connect the segues as you would normally and it should appear.

**Comment by aaizuss** [comment]
this didn't work :( I can create it manually though
