### ISSUE TITLE
Contact Detection

### ISSUE THREAD

**Issue by hbennett766** [uchicago-mobi/2016-Spring-Forum#125]
My frog object and car object don't send contact recognition, and I'd rather the frog not be quite so invincible. Here's the relevant code:

// in mark: properties
let frogCategory: UInt32 = 1 << 0
let carCategory: UInt32 = 1 << 1

// in didMoveToView
self.physicsWorld.contactDelegate = self 

// in method called by didMoveToView
frog.physicsBody = SKPhysicsBody(rectangleOfSize: frog.size)
frog.physicsBody?.dynamic = false
frog.physicsBody?.usesPreciseCollisionDetection = true
frog.physicsBody?.categoryBitMask = frogCategory
frog.physicsBody?.contactTestBitMask = carCategory
frog.physicsBody?.collisionBitMask = carCategory

// in method called by didMoveToView
car.physicsBody = SKPhysicsBody(rectangleOfSize: car.size)
car.physicsBody?.dynamic = false
car.physicsBody?.usesPreciseCollisionDetection = true
car.physicsBody?.categoryBitMask = carCategory
car.physicsBody?.contactTestBitMask = frogCategory
car.physicsBody?.collisionBitMask = frogCategory

// contact method
func didBeginContact(contact: SKPhysicsContact) {
        // do stuff here
        // regardless of what's here, the method isn't getting called at all. I've tested with breakpoints and print statements, neither of which are ever reached
    }

Any ideas on how to fix it? Thanks!

**Comment by tabinks** [comment]
@hbennett766  I'll look at your repo....

**Comment by tabinks** [comment]
For those that are curious:  'dynamic=true' on the cars did the trick.
