### ISSUE TITLE
"Modern" Core Data (enjoy @msylvester)

### ISSUE THREAD

**Issue by aaizuss** [uchicago-mobi/2016-Spring-Forum#129]
[Core Data: how to make the code more readable and less error-prone by using protocols and protocol extensions](https://realm.io/news/tryswift-daniel-eggert-modern-core-data/?utm_campaign=This%2BWeek%2Bin%2BSwift&utm_medium=email&utm_source=This_Week_in_Swift_90)

**Comment by tabinks** [comment]
This approach is pretty popular and there are some objective c versions that do a similar thing.  Typically you would end up doing something similar for a production app....making special functions that make it easier to use your data.
