### ISSUE TITLE
App store fees can drop to 15%, according to Phil Schiller

### ISSUE THREAD

**Issue by prazgaitis** [uchicago-mobi/2016-Spring-Forum#134]
http://www.theverge.com/2016/6/8/11880730/apple-app-store-subscription-update-phil-schiller-interview

**Comment by tabinks** [comment]
Here's the official announcement...including paid search results placement.
https://developer.apple.com/news/

I'm trying to envision what this will actually mean:
- Big companies will dump money to buy the best add placement.  So, no real change.
- There will be very few paid-up-front apps.  Everyone will try subscriptions.
- Subscriptions will be really annoying for customers who will end up managing them for almost every app they have.

**Comment by prazgaitis** [comment]
App idea: an app that manages your existing app subscriptions....but charges you a subscription fee
