### ISSUE TITLE
Earlier Office Hours Sunday?

### ISSUE THREAD

**Issue by aaizuss** [uchicago-mobi/2016-Spring-Forum#14]
Auto layout is killing me (I want to put a bunch of image views on each page and nothing is cooperating). @susanstevens can you start your office hours earlier on Sunday?

**Comment by susanstevens** [comment]
@aaizuss I could move them to 3-5pm.  Would that help?

**Comment by aaizuss** [comment]
@susanstevens Actually I have a meeting from 4-5 so it's probably better to keep then 4-6 (i can try to leave my meeting early). Thanks though!
