### ISSUE TITLE
Problem with AVSpeechSynthesizerDelegate

### ISSUE THREAD

**Issue by msylvester** [uchicago-mobi/2016-Spring-Forum#15]
I am getting the following error using the delegate  AVSpeechSynthesizerDelegate:

AXSpeechAssetDownloader|error| ASAssetQuery error fetching results (for com.apple.MobileAsset.MacinTalkVoiceAssets) Error Domain=ASError Code=21 "Unable to copy asset information"

help?

**Comment by susanstevens** [comment]
Yep, I'm seeing the same error.  Looks like it's an AVSpeechSynthesizer bug.  Is it causing your app to crash or creating any other problems?  (If not, you can just ignore it.)

**Comment by msylvester** [comment]
@susanstevens it doesn't make the app crash, but, i think it might disable playback a second time.  I.e. I have a button 'readToMe,' which, when pressed, may not read the text a second time when pushed.

**Comment by susanstevens** [comment]
Hmmm... That's not happening for me.  Is it happening every time?  If you've hit the read-to-me button once, does it never work the second time?  Or does it sometimes work the second time and sometimes not?

**Comment by tabinks** [comment]
Try running on device (while connected) and see if you get the error (and any weird behavior).  `AVSpeechSynthesizer` does have issues in the simulator, but I haven't seen it actually effect the performance (ie. it works, but throws debug messages).
