### ISSUE TITLE
.git merging and Xcode projects w/ storyboard

### ISSUE THREAD

**Issue by msylvester** [uchicago-mobi/2016-Spring-Forum#17]
@tabinks can we go over this in class? 

It is not straight forward. 

Also, I think I am the front runner for the # of posts award.  

Posts on fleek.

**Comment by susanstevens** [comment]
Are you running into a particular problem?  Merge conflicts?

**Comment by tabinks** [comment]
What problems are you having?  Post your questions here so I can figure out what the issue is.
