### ISSUE TITLE
Layout on iPad Pro vs iPad

### ISSUE THREAD

**Issue by aaizuss** [uchicago-mobi/2016-Spring-Forum#18]
My pages are laid out properly when I test on the iPad Pro, but everything gets squished together on the iPad. Are you going to be testing on multiple devices? Can you tell us what you're testing on so I can make sure it looks okay?

**Comment by aaizuss** [comment]
https://developer.apple.com/library/ios/documentation/UserExperience/Conceptual/MobileHIG/LayoutandAppearance.html says iPad and iPad Pro use Regular size class in both dimensions, which is where I've been laying out my pages and adding constraints in storyboard, but then the preview window shows some differences

**Comment by susanstevens** [comment]
We'll only be testing on iPad, not iPad Pro.
