### ISSUE TITLE
Assignment 2 Repository Link (and Tips)

### ISSUE THREAD

**Issue by tabinks** [uchicago-mobi/2016-Spring-Forum#25]
Repo Link: https://classroom.github.com/assignment-invitations/c28a2f5d02c261fe2c8d794f5e65fa5a

I also created a github team (@uchicago-mobi/mpcs51030-2016-winter) for this class, so please accept the invitation you should have received in your email.

**Comment by tabinks** [comment]
Tip 1: You're CoreData Model should be identical between your data-seeding application and your user application.  You can just copy the `.xcdatamodeld` between the projects to ensure that it is identical.  If they are not identical, you will get an error about the data not matching the model.

**Comment by tabinks** [comment]
Tip 2:  You need to copy all the sqlite files (.sqlite, .sqlite-shm, .sqlite-wal) that are generated.  These files are for features in sqlite databases, not specific to anything in CoreData.

![screenshot 2016-04-13 12 00 34](https://cloud.githubusercontent.com/assets/93689/14502170/97d04b80-016f-11e6-90a8-22a726e225cd.png)

**Comment by susanstevens** [comment]
If you're having trouble finding the .sqlite files, here are a couple helpful links.

http://stackoverflow.com/questions/24133022/ios-8-store-sqlite-file-location-core-data
http://www.macworld.com/article/2057221/how-to-view-the-library-folder-in-mavericks.html

**Comment by lw334** [comment]
I copied the sqlite3 files and I'm getting 'NSInternalInconsistencyException', reason: 'NSFetchRequest could not locate an NSEntityDescription for entity name 'App'' in my new app... I copied the data model file into the new one,renamed it and created NSmanagedobject subclass from it. Also deleted the app etc...
