### ISSUE TITLE
How to import secondary app?

### ISSUE THREAD

**Issue by aljc** [uchicago-mobi/2016-Spring-Forum#28]
The specs suggest that we write a secondary app to make the JSON request / persist the data into the Core Data store.  How then exactly would we connect that secondary app to our primary app?

**Comment by susanstevens** [comment]
Once you've made the application that makes the API request and downloads the data into a Core Data store, you should copy the Core Data store into your main app.  You can right click on the Core Data store and select "View in Finder" and then drag and drop it into the project navigator (the left panel that lists all your files) of your main app.

**Comment by susanstevens** [comment]
Also make sure you take a look at issue #25

**Comment by tabinks** [comment]
The data seeding app and the user app don't have any connection.  They are completely independent of each other.  They should be two separate Xcode projects.
