### ISSUE TITLE
Games only?

### ISSUE THREAD

**Issue by aaizuss** [uchicago-mobi/2016-Spring-Forum#30]
The assignment says we're making a game store, but there doesn't appear to be a way to limit the search API to apps in the Games category. The json has a "genres" key with an array of values including "Games". When our app downloads the json, do we need to filter it to only include apps that list "Games" as a value for "genres"?

**Comment by susanstevens** [comment]
You shouldn't need to do any filtering.  There's a genre id parameter that you can pass in your url.

https://affiliate.itunes.apple.com/resources/documentation/genre-mapping/
