### ISSUE TITLE
Some basic questions about the Core Data Model

### ISSUE THREAD

**Issue by aaizuss** [uchicago-mobi/2016-Spring-Forum#31]
What does this (bolded parts) mean? I understand that you want us to pull out the nouns from the description, but what do you mean by "that will serve as you query search terms" and that an Entity should store them? Is this going to be part of how our search implementation works? I'm also confused by what the data model can look like - right now I have an Entity called App with attributes from the JSON that i want to show up in the table view. And you say "use the same naming conventions returned from the JSON" - I assume this means to call the attributes exactly what the json calls keys (like "artworkUrl60" for the icon).

"During the import process use NSLinguisticTagger to **identify a subset of tokens from the app description that will serve as you query search terms (e.g. use only nouns).** These tokens should be associated with the applications model in the Core Data store (i.e. create an Entity or Entities to store them). You will be using NSPredicate to search for applications using these terms in your application (this is the field you will be searching against). The exact implementation details and tagging scheme is up to you."

Another thing - when I type import CoreData, the autocomplete thing shows a red line through it - what's up with that?

**Comment by tabinks** [comment]
The idea is to reduce the words in your searchable description to make the terms being searched more meaningful.

Yes, name your attributes the same as the JSON.

Not sure about the red line.  Can you post a screen shot?

**Comment by aaizuss** [comment]
![screen shot 2016-04-18 at 9 58 22 am](https://cloud.githubusercontent.com/assets/11274851/14608631/25bab612-054c-11e6-9c89-b592a6eafbfd.png)

**Comment by susanstevens** [comment]
@aaizuss Did you name your project CoreData? That might cause a namespace conflict.  What error is Xcode giving you?

**Comment by aaizuss** [comment]
@susanstevens I named the project AppData, but I have a singleton class called CoreDataStack

**Comment by tabinks** [comment]
@aaizuss Did you check off the core data box in your project creations dialogue?  My guess is that its not importing the framework in your project.

**Comment by aaizuss** [comment]
@tabinks I did, and it must have imported the framework because the core data stack stuff was in the AppDelegate (I cut and pasted it into its own class though). It lets me import CoreData and doesn't give me any errors or warnings besides that initial strikethrough, though.

**Comment by aaizuss** [comment]
Anyway, I'm still working on the Core Data app and there are lots of gaps in my knowledge right now (I can mostly follow the slides and the playground example, but since we're getting the data from JSON, it's a bit different) so hopefully I can ask questions before or after class. I defined a data model in the data model file and tokenized the info that I need from the JSON but I don't know how to actually store everything in the Core Data store. In the example you manually added users "Homer" and "Marge." I have a function that, from the result of the network call, makes an array called apps, which is an array of tuples`[(name: String, icon: String, price: String, rating: Float, screenshots: [String])]` so I can hopefully iterate over that and add each app and its attributes. I'm stuck now though.
