### ISSUE TITLE
WWDC 2016 Scholarship

### ISSUE THREAD

**Issue by tabinks** [uchicago-mobi/2016-Spring-Forum#37]
<img width="979" alt="screenshot 2016-04-18 23 17 46" src="https://cloud.githubusercontent.com/assets/93689/14627649/d3a02824-05bb-11e6-993b-ce8f1109d0a5.png">

**Comment by tabinks** [comment]
https://developer.apple.com/wwdc/scholarships/

You can submit your scholarship application until Sunday, May 1 at 5:00 p.m. PDT. All applicants will be notified of their status by Monday, May 9.

_I'd be happy to discuss any ideas you have for you submissions_

**Comment by msylvester** [comment]
awesome ++

**Comment by tabinks** [comment]
@uchicago-mobi/mpcs51032-2016-spring If you are planning on submitting something for this, please talk with me.  I have some insights on what they will be looking for...

**Comment by aaizuss** [comment]
@tabinks I'm going to office hours today so I'll talk to you then

**Comment by jao9898** [comment]
hello, I'm sorry, but what exactly is the theme of the app suppose to be?
isn't it suppose to be an app about yourself?
The deadline is very soon so I hope someone responds quick, thank you.

**Comment by susanstevens** [comment]
Take a look at the guidelines: https://developer.apple.com/wwdc/scholarships/Scholarship-Guidelines-and-Terms.pdf.  It can be any app.

**Comment by yiqin** [comment]
One more day to submit the application! 🚀
