### ISSUE TITLE
separate entity for keywords

### ISSUE THREAD

**Issue by lw334** [uchicago-mobi/2016-Spring-Forum#38]
Are we mapping the words to the apps or can we just store the words as a field of the app?

**Comment by susanstevens** [comment]
The keywords should be an attribute of your app entity, not a separate entity.

**Comment by lw334** [comment]
" During the import process use NSLinguisticTagger to identify a subset of tokens from the app description that will serve as you query search terms (e.g. use only nouns). These tokens should be associated with the applications model in the Core Data store (i.e. create an Entity or Entities to store them). " @tabinks ?

**Comment by tabinks** [comment]
@susanstevens is correct.  Create a new attribute on your application entity that store the tokenized descriptions.  The basic idea is to not store words that won't be useful in searches (or would match promiscuously).
