### ISSUE TITLE
Finding and Loading Model

### ISSUE THREAD

**Issue by aaizuss** [uchicago-mobi/2016-Spring-Forum#39]
I tried fetching data in my GameStore app, and I get "fatal error: unexpectedly found nil while unwrapping an Optional value" and it highlights the managedObjectModel in my Core Data Stack. Is this what everyone was trying to figure out yesterday? 
![screen shot 2016-04-19 at 2 22 59 pm](https://cloud.githubusercontent.com/assets/11274851/14652518/47f586a0-063a-11e6-80c2-2ea5f6571a13.png)

is my modelURL wrong? The entire core data stack was copied and pasted from my seeding app.

Also, I get an error when I try to cast my results as App (which is the class for my core data objects) 

In my cellForRowAtIndexPath function, I have
`let app = fetchedResultsController.objectAtIndexPath(indexPath) as! App`
But I have a compile time error that says "Use of undeclared type 'App' "

Here is what my project navigator looks like:
![screen shot 2016-04-19 at 3 00 08 pm](https://cloud.githubusercontent.com/assets/11274851/14653627/73776794-063f-11e6-8a59-5ac2a5cebc31.png)

**Comment by tabinks** [comment]
Look at #36 and pay attention to the URLs.  You should be looking for your model in the `NSMainBundle` not documents directory.

**Comment by aaizuss** [comment]
@tabinks That didn't fix it. (lines 35 and 36 are where I follow what Paul did)
![screen shot 2016-04-19 at 4 21 03 pm](https://cloud.githubusercontent.com/assets/11274851/14656032/e4b2ce16-064a-11e6-9494-defc537fcc1c.png)

("AppData" is the name of my seeding app)

**Comment by tabinks** [comment]
Try changing momd to mom.   If it works I'll tell you why.

**Comment by tabinks** [comment]
Actually, now that I look at your project navigator I don't see the model file. Did you remember to copy that over?

**Comment by tabinks** [comment]
Also make sure that you are including the model file in embedded framework target.

**Comment by aaizuss** [comment]
@tabinks whoops okay I'm adding the model file now. And I assume you mean in the "Add to targets" option to select the GameStore target and the CoreDataKit target.

**Comment by aaizuss** [comment]
@tabinks update: So this fixes the crashing but I when it runs, I get
CoreData: warning: Unable to load class named 'GameStore.App' for entity 'App'.  Class not found, using default NSManagedObject instead.

And I assume that's related to this issue (which I still have):

> Also, I get an error when I try to cast my results as App (which is the class for my core data objects)
> In my cellForRowAtIndexPath function, I have
> `let app = fetchedResultsController.objectAtIndexPath(indexPath) as! App`
> But I have a compile time error that says "Use of undeclared type 'App' "

**Comment by tabinks** [comment]
@aaizuss We're getting there....I'm going to guess that you didn't copy over (or generate new) the `NSManagedObject` subclasses for your `App` entity.

**Comment by aaizuss** [comment]
@tabinks Ahh thanks! I'm sorry for not paying closer attention!
