### ISSUE TITLE
session 4 lecture notes 

### ISSUE THREAD

**Issue by msylvester** [uchicago-mobi/2016-Spring-Forum#41]
Couldn't access them via the link.  Tried on both safari and chrome.

**Comment by tabinks** [comment]
Ask Hanz!

https://ff8276a3d76177159b643022d4cc86d3f633fc86.googledrive.com/host/0B3XzcKIiWyccdlgtOW42N0xQZjQ/MPCS51032/2016-Spring/Session4/MPCS51032-2016-Spring-Lecture4.pdf

Have a pepsi.

**Comment by tabinks** [comment]
@msylvester Fixed.
