### ISSUE TITLE
Retrieving Images from CoreData

### ISSUE THREAD

**Issue by aaizuss** [uchicago-mobi/2016-Spring-Forum#42]
I know that I'm successfully saving icon images as Binary Data in my seed app like so:
![screen shot 2016-04-19 at 8 21 47 pm](https://cloud.githubusercontent.com/assets/11274851/14660598/63df0d3c-066c-11e6-9aa0-3ae1bcc72b13.png)

Now I'm trying to display the icon in my table view cells, and I keep getting unexpectedly found nil while unwrapping an optional (or, if I use if let, obviously the app runs and the images don't show up because it never gets inside the if). I've tried a couple ways of doing this:
1. ![screen shot 2016-04-19 at 8 24 09 pm](https://cloud.githubusercontent.com/assets/11274851/14660643/c79287fa-066c-11e6-9250-f32ce34f9bc0.png)
2. ![screen shot 2016-04-19 at 8 25 24 pm](https://cloud.githubusercontent.com/assets/11274851/14660665/e40434b0-066c-11e6-8a92-0779d69c04c3.png)

In both cases, it it finds nil when unwrapping "artworkUrl60" (which is the attribute name). Suggestions? StackOverflow says this is the way to pull images out of CoreData.

**Comment by susanstevens** [comment]
Are you able to retrieve other attributes from your CoreData entity?  Is there something different about how you're saving the image data?  The unexpected nil error suggests that the image data isn't being saved correctly.

**Comment by aaizuss** [comment]
@susanstevens I successfully retrieve the app name and developer name and they show up in my table view. And yes, I save the image data differently in my seed app because I use the do/catch block and get the contents of the URL and convert it to NSData. But in my seed app, I also printed the binary data that I save and there's a lot there... 
![screen shot 2016-04-19 at 8 37 25 pm](https://cloud.githubusercontent.com/assets/11274851/14660865/8d9ab7aa-066e-11e6-8bd7-5804b30c8e2c.png)

So maybe I'm not saving properly (you can see how I do so in my original post) but I'm definitely saving something.

**Comment by susanstevens** [comment]
Hmmm... I don't see where you're actually saving anything in your original post.  You should have an `NSManagedObject` (is that what `app` is?), and then you should call `app.setValue(imageData, forKey: "artworkUrl60")`.  Make sure you call `managedContext.save()` inside of another `do-try-catch` block at the end.

**Comment by aaizuss** [comment]
@susanstevens Yes,  that's what `app` is. And I thought that `app.artworkUrl60 = imageData` saves it. 

I save everything like `app.artistName = result["artistName"] as? String`

And at the end, I call `data.saveContext()` (data is my CoreData Stack the instance of my core data singleton in my seed app)

I just tried your way with app.setValue and `data.managedObjectContext.save` (and I copied in the new sql files after changing the code in my seed app), but I have the same problem.

**Comment by aaizuss** [comment]
New issue: I'm printing the app names in my seed app as I add attributes, and after iterating over a lot of the json, the app crashes: 
![screen shot 2016-04-19 at 10 28 12 pm](https://cloud.githubusercontent.com/assets/11274851/14662664/0925e5b6-067e-11e6-9b82-468f1f25c1c3.png)

This is exhausting. I'm skipping a class to go to office hours tomorrow though

**Comment by prazgaitis** [comment]
same issue over here. I know i have the right data because i can see the actual image when looking at the data in sqlitebrowser

**Comment by aaizuss** [comment]
@prazgaitis I fixed it by changing the say I save:
![screen shot 2016-04-20 at 10 44 53 pm](https://cloud.githubusercontent.com/assets/11274851/14697444/846ba438-0749-11e6-8430-d7b0c8a9f63c.png)

And using `setValue` to set the attributes. I also deleted the apps from simulator before re running.
