### ISSUE TITLE
Tip: Saving Screenshot URLs to Core Data as an array

### ISSUE THREAD

**Issue by aaizuss** [uchicago-mobi/2016-Spring-Forum#45]
Add an attribute to your CoreData Model (mine is screenshotUrls) with type Transformable.

Then, when you make your class, change the type to [String]? so you'll have
`@NSManaged var screenshotUrls: [String]?`

In your ViewController, save from the JSON like this:
`app.screenshotUrls = result["screenshotUrls"] as? Array`

**Comment by tabinks** [comment]
Note: You will need to go into your subclass file and change the type to `[String]`.  By default it will be an `NSObject`.

`@NSManaged var screenshotUrls: NSObject?`
to 
`@NSManaged var screenshotUrls: [String]?`
