### ISSUE TITLE
Saving to Wishlist without using CloudKit

### ISSUE THREAD

**Issue by aaizuss** [uchicago-mobi/2016-Spring-Forum#46]
In class, you said we wouldn't be using CloudKit (unless I'm going crazy). So in the ExtendThisApp playground in the DataKitManager file, we should ignore the CloudKit stuff and just look at the LocalDefaultsManager code, right?

**Comment by tabinks** [comment]
Yes.  Ignore the CloudKit class in the DataKitManager.  We'll talk about the CloudKit implementation on Monday.

Use the LocalDefaultsManager to store wishlist in `NSUserDefaults` using App Groups.
