### ISSUE TITLE
Saving to Wishlist: What exactly do we save to user defaults?

### ISSUE THREAD

**Issue by aaizuss** [uchicago-mobi/2016-Spring-Forum#48]
You say that the wishlist table view cell should at least show  the application's icon, name, and date added. Does that mean that when we save to user defaults, we should make some sort of data structure that contains those 3 things (like a dictionary, for example)? And then when we display the info in the cell, we just get the object from user defaults. Or should we just save one attribute, like the app name, and then to display the other info, fetch the entity from core data (given the name) and get the necessary attributes (I don't even know if that's possible/it might defeat the purpose of storing to user defaults)?

**Comment by susanstevens** [comment]
I'd recommend taking the former approach, not trying to fetch the entity from Core Data.  If the user adds an app to their wishlist from the share extension, it might not even exist in your Core Data store.

**Comment by tabinks** [comment]
If you look at the sample project, you will see that I did what you are suggesting. I made a dictionary that holds the icon title and date.
