### ISSUE TITLE
lol i got a segfault 

### ISSUE THREAD

**Issue by aaizuss** [uchicago-mobi/2016-Spring-Forum#50]
i've only ever gotten segfaults when programming in C?

All I did was add a file called WishTableViewController (I have a wishlist tab in my app).
![screen shot 2016-04-21 at 11 45 27 pm](https://cloud.githubusercontent.com/assets/11274851/14731935/2880331e-081b-11e6-8d85-3421a8556cc4.png)

I tried deleting the file and then the app compiles and runs. When I add the file back, it segfaults! There are no warnings before compiling.

**Comment by susanstevens** [comment]
Here are some steps to try (before adding WishTableViewController back into your project)...
1. Clean your project (Product > Clean)
2. Delete derived data (Window > Projects, then find your current project and click the "Delete" button next to derived data)
3. Reset the simulator (Simulator > Reset Contents and Settings)
4. Close and re-open Xcode

Then try adding the WishTableViewController back into your project.

**Comment by aaizuss** [comment]
@susanstevens I tried this and it was going well - I added file back (by actually retyping everything). When I first create the file and compile, the app runs. But when I edit the cellForRowAtIndexPath function and try to compile, I get the segfault.

**Comment by aaizuss** [comment]
@susanstevens I also keep getting a notification that an internal error occurred and source editing functionality is limited as I edit the file

**Comment by aaizuss** [comment]
interesting: http://blog.bellebethcooper.com/xcode-bug.html (I'm not doing anything with JSON in this app and I don't think the fix is relevant, but she also had the segfault + internal error issue)

**Comment by aaizuss** [comment]
Also, since adding the file back but before recompiling, I'm suddenly getting an error in my other table view controller where I import my embedded framework (called CoreDataKit). It says 
"Cannot load underlying module for 'CoreDataKit'." I haven't gotten this error before. 

When I compile, this error goes away and I get a seg fault

**Comment by aaizuss** [comment]
I wonder if it's actually a problem in my AppDetailViewController, which is where I save the app info to user defaults for the wish list feature. I'm saving a dictionary to user defaults, and the dictionary contains multiple types. I initialize it like this `var appDict = ["Name": "", "Icon": NSData(), "Date": ""]` which might be bad. Then I add the info to the dictionary like:

`appDict["Name"] = app!.trackName!`
`appDict["Icon"] = app!.artworkUrl60`
`appDict["Date"] = getDateString()`

and save to user defaults with `defaults.add(object: appDict)` where defaults is `LocalDefaultsManager.sharedInstance`

In `WishTableViewController`, this is my cellForRowAtIndexPath:

![screen shot 2016-04-22 at 10 07 29 am](https://cloud.githubusercontent.com/assets/11274851/14745712/24cf723c-0872-11e6-8eda-7a389adca03b.png)

**Comment by tabinks** [comment]
> "Cannot load underlying module for 'CoreDataKit'." 

You get this error if the framework isn't compiled yet.  Switch targets to the framework and the build.  Then switch back and it should find it.

**Comment by aaizuss** [comment]
@tabinks I'm still getting a segfault... do you have any advice based on what I've posted?

**Comment by tabinks** [comment]
@aaizuss Not anything that @susanstevens didn't suggest.  Try setting a break point in your table at every lifecycle method (eg. viewDidLoad, etc.).  See how far you can get before calling `cellForRowAtIndexPath`. Report back with what you get.  

Also, put it (the broken one)  in a branch in your repo and I'll try to download and take a look.  I won't be able to do this until tonight/tomorrow

**Comment by aaizuss** [comment]
@tabinks Okay, I put the broken one in a branch.

**Comment by aaizuss** [comment]
I think I fixed it - since I'm saving the name/date/icon to a dictionary, when I access them in the TableViewController, I first need to case the object I get from indexPath.row as NSDictionary, and then for each item in the dictionary, I need to cast the proper type (in my case i'm storing 2 strings and NSData)

**Comment by tabinks** [comment]
@aaizuss 👍
