### ISSUE TITLE
SKStoreProductViewController not displaying

### ISSUE THREAD

**Issue by aaizuss** [uchicago-mobi/2016-Spring-Forum#52]
I have a button that's supposed to launch an SKStoreProductViewController. When the button is tapped, the IBAction function calls a function `showStoreView`, which I wrote to initialize a `storeViewController`, set its delegate to `self`, and then call `loadProductWithParameters`.

When I tap the button, I know that the `showStoreView` function gets called, but it seems like `loadProductWithParameters` doesn't get called. I call it like this:

![screen shot 2016-04-23 at 7 33 06 pm](https://cloud.githubusercontent.com/assets/11274851/14764771/3a5690d6-098a-11e6-8335-a3a00f598624.png)
and neither of these print statements are printed. There is hardly any documentation about SKStoreProductViewController, and StackOverflow is letting me down

`params` is the id for the app (I've printed appID, and it's correct): `let params = [SKStoreProductParameterITunesItemIdentifier: NSNumber(integer: appID)]`

**Comment by susanstevens** [comment]
Are you testing in the simulator?  I think you need to test on a device, since the app store doesn't exist on the simulator.
