### ISSUE TITLE
Exception: 'Attempt to insert non-property list object for key wishlist'

### ISSUE THREAD

**Issue by prazgaitis** [uchicago-mobi/2016-Spring-Forum#53]
When I go to save an app to NSUserDefaults in the sharedAppGroup, I'm getting this error:

``` Swift
2016-04-24` 08:50:55.752 GameStore2[22156:5620397] Attempt to set a non-property-list object (
    "<GameStore2.LocalApp: 0x7f9890480980>"
) as an NSUserDefaults/CFPreferences value for key wishlist
2016-04-24 08:50:55.766 GameStore2[22156:5620397] *** Terminating app due to uncaught exception 'NSInvalidArgumentException', reason: 'Attempt to insert non-property list object (
    "<GameStore2.LocalApp: 0x7f9890480980>"
) for key wishlist'
```

My LocalApp class implements NSCoding, and it was saving fine when I was storing it to NSUserDefaults _outside_ of the app group. My code to save the object is pretty much identical to the sample project. [Gist here](https://gist.github.com/prazgaitis/3d3e28c5db623e111a3a385dfebdedc0)

Here's how im trying to add it to the wishlist right now:

``` Swift
@IBAction func addToWishlist(sender: AnyObject) {
     let wishlist = LocalDefaultsManager.sharedInstance.currentList()
     LocalDefaultsManager.sharedInstance.add(object: app!)    
     print("added app to wishlist")
}
```

Wondering if anyone else is getting this problem - let me know if i missed something in the notes or sample projects.

**Comment by susanstevens** [comment]
Remember that you can only store certain types to `NSUserDefaults`.

From the Apple documentation: 

"The NSUserDefaults class provides convenience methods for accessing common types such as floats, doubles, integers, Booleans, and URLs. A default object must be a property list, that is, an instance of (or for collections a combination of instances of): NSData, NSString, NSNumber, NSDate, NSArray, or NSDictionary. If you want to store any other type of object, you should typically archive it to create an instance of NSData."
