### ISSUE TITLE
Getting app id from iTunes Url

### ISSUE THREAD

**Issue by aaizuss** [uchicago-mobi/2016-Spring-Forum#55]
I'm saving the iTunes URL returned by the API as a string (which looks like: "https://itunes.apple.com/us/app/toddlers-preschool-zoo-animals/id505924849?mt=8&uo=4")

To open the SKStoreProductViewController, I need to grab the id, so for the link above it would be "505924849"

I'm trying to get this substring with a regex search - the idea is to get the range of the string from the index of "id" to the question mark. To escape the question mark, you use 2 backslashes.

First I had this: 
`let range = url.rangeOfString("(?<=id)(?=\\?)", options: .RegularExpressionSearch)`
`let id = url.substringWithRange(range!)`
(and then I convert the id to an Int and return it)

But when I print out what the range is, I always get nil. What am I doing wrong?

I also realized that it's likely that the string has "id" somewhere before the actual id (perhaps in the name of the app). So now I'm trying to match a string that has id and then a number. I know you match numbers with "\d" but I don't know how to combine these. 

Or, if this is too complicated, my other idea is to find the end index like:
`let endIndex = url.characters.indexOf("?")` and then the subtract some number to get the start index, and get the substring that way (I think the app ids are all 9 digits), but I haven't figured out how to actually do that either.

Suggestions?

**Comment by susanstevens** [comment]
I'd go with your second idea.  Once you get the index of `?`, you can subtract 9 to get the start index of the id.  Then you can use `substringWithRange` to get the substring you need.

**Comment by tabinks** [comment]
I would suggest: 1) Split the string on "/id" 2) Split that string on "?"

The reason to split the first string on "/id" and not "id" is so you don't match titles that have "id" in them.

**Comment by Eric-Warehime** [comment]
You don't have to parse the url. The id is given in the api call: "trackId": 1234567.

**Comment by aaizuss** [comment]
@Eric-Warehime ahh i was looking for that... well I already parsed it and I don't want to update my data model again haha

**Comment by lw334** [comment]
Totally sympathize with Amanda. It freaks me out every time I need to update the data model. But I did update it..... and I did freak out. @aaizuss @Eric-Warehime
