### ISSUE TITLE
Dylib not safe for use in application extensions

### ISSUE THREAD

**Issue by aaizuss** [uchicago-mobi/2016-Spring-Forum#56]
I'm getting the warning: "Linking against a dylib which is not safe for use in application extensions" for both of my extensions. 

[Apple Documentation](https://developer.apple.com/library/ios/documentation/General/Conceptual/ExtensibilityPG/ExtensionScenarios.html) says

> To configure an app extension target to use an embedded framework, set the target’s “Require Only App-Extension-Safe API” build setting to Yes. If you don’t, Xcode reminds you to do so by displaying the warning “linking against dylib not safe for use in application extensions”

My target's build setting is set correctly, so why am I still getting this warning? StackOverflow says that there isn't a way to suppress this warning. Is that okay?

**Comment by tabinks** [comment]
We can discuss tomorrow, but check to make sure you aren't using a framework that is not allowed.

**Comment by aaizuss** [comment]
@tabinks What does that mean? How do I know if I'm using a framework that isn't allowed?

**Comment by msylvester** [comment]
@aaizuss:
"A software framework, in computer programming, is an abstraction in which common code providing generic functionality can be selectively overridden or specialized by user code providing specific functionality"

Hope this helps 👍
