### ISSUE TITLE
App Groups without developer account?

### ISSUE THREAD

**Issue by aljc** [uchicago-mobi/2016-Spring-Forum#57]
Is there any way I can test my Share Extension (which requires enabled App Groups in order to write to shared NSUserDefaults) without an active dev program account?  For example, can I enroll in the University account program?

**Comment by susanstevens** [comment]
I don't think we have a University account set up for this class, and it looks like a paid developer account is required for creating app groups.  Amanda discovered that it takes a couple days to process a paid developer account, though.  I'll bring my computer to class & office hours today, though, so you can try running it with my account.  Just make sure you have everything pushed up to github.

**Comment by tabinks** [comment]
@aljc @uchicago-mobi/mpcs51032-2016-spring Please let me know if who doesn't have a paid developer account.  I will activate the University Developer accounts.

**Comment by aaizuss** [comment]
@tabinks I don't have one (yet)
