### ISSUE TITLE
Failed to communicate with Apple.....

### ISSUE THREAD

**Issue by lw334** [uchicago-mobi/2016-Spring-Forum#59]
Tried to add an app group so that my extensions can share data but I failed to create the group and get this failed to communicate with Apple error.... No idea why. I heard it's a new version of Xcode thing. Does anyone else have this error?

<img width="675" alt="screenshot 2016-04-25 03 12 08" src="https://cloud.githubusercontent.com/assets/11820006/14777589/b6c939c0-0a93-11e6-83f4-67e45323141e.png">

**Comment by susanstevens** [comment]
See #57
