### ISSUE TITLE
Office Hours Schedule

### ISSUE THREAD

**Issue by tabinks** [uchicago-mobi/2016-Spring-Forum#6]
I will not be having office hours this week due to my Spring Break!!!!  I will make them up Monday before/after class this week.

For normal office hours, I am planning to hold them either Wednesday or Thursday around noon again.  Please let me know which would be better for you.  I'll try to see if their is a consensus.

**Comment by aaizuss** [comment]
Wednesday works best for me (I have class on Thursday from 10:30 - 1:20)

**Comment by shuaib88** [comment]
Thursday would be best for me. Anytime would be good (Maybe 1:00 or 1:30 start time?)

**Comment by lw334** [comment]
Wednesday around noon before 1:30 works for me. Thanks!
