### ISSUE TITLE
Command failed due to segmentation fault: 11

### ISSUE THREAD

**Issue by msylvester** [uchicago-mobi/2016-Spring-Forum#64]
Has anyone seen this Xcode error?  It is not a pretty one that I cannot figure out how to solve..

**Comment by tabinks** [comment]
Can you post a screenshot of the entire dump?

**Comment by msylvester** [comment]
<img width="729" alt="screenshot 2016-04-27 16 35 17" src="https://cloud.githubusercontent.com/assets/8303700/14868949/0f64e5a8-0c96-11e6-9a6d-620c10e16186.png">
<img width="701" alt="screenshot 2016-04-27 16 35 09" src="https://cloud.githubusercontent.com/assets/8303700/14868950/11bf8a56-0c96-11e6-92ce-6c7a9b108d9f.png">
<img width="746" alt="screenshot 2016-04-27 16 34 59" src="https://cloud.githubusercontent.com/assets/8303700/14868951/133afc1c-0c96-11e6-8a2b-7ac49d709607.png">

**Comment by msylvester** [comment]
IT's some kind of parsing json error.  I have seen similar posts regarding it.  IF I comment out the following it compiles, 

```
do {

  let object = try NSJSONSerialization.JSONObjectWithData(data!, options: .AllowFragments)
  //print(object)


  if let dictionary = object as? [String: AnyObject] {

    let lengthArray = object["galleryInfo"] as? [String: AnyObject]

    for index in 0...lengthArray?.count {
```

**Comment by msylvester** [comment]
Went a different route, but problem not fixed

**Comment by susanstevens** [comment]
What line is it crashing on?
