### ISSUE TITLE
iPhone, iPad, or Universal? 

### ISSUE THREAD

**Issue by aaizuss** [uchicago-mobi/2016-Spring-Forum#7]
Should the first assignment be a universal app? Or can we choose one device?
Edit: I see you answered this question on the winter forum - should we make sure the app looks good on all iPad sizes?

**Comment by tabinks** [comment]
iPad only, whatever orientation you prefer.  There should be no changes to make between iPad and iPad mini.  They are the same point size...just different pixel size.
