### ISSUE TITLE
WatchOS

### ISSUE THREAD

**Issue by tabinks** [uchicago-mobi/2016-Spring-Forum#70]
If you are thinking about adding a watch app to your submission, I would recommend watching all of these videos (in this order).  This will show you what is capable on the watch and all the different options to interact with it.  I am putting together a simple playground for a watch app I will post later today.
- https://developer.apple.com/videos/play/wwdc2015/105/
- https://developer.apple.com/videos/play/wwdc2015/207/
- https://developer.apple.com/videos/play/wwdc2015/802/
- https://developer.apple.com/videos/play/wwdc2015/208/
- https://developer.apple.com/videos/play/wwdc2015/228/

I would recommend downloading first and then watching at 1.5x speed.  It will save you a couple hours :)

**Comment by tabinks** [comment]
There's a new project in the playground 2016-Session6-WatchInterFaces showing how to pass data back and forth between the watch and iOS app.  It is really simple but should get you started.  Remember this only passes data, you still need to figure out what to do with it and how to store it (ie. app groups).

**Comment by tabinks** [comment]
To run in simulator, make sure to choose the "Watch App".  In this scheme you will only see console output form the watch app.  To see both iOS and Watch console output, go to "Debug > Output Logs" in the Simulator (command-L).

**Comment by tabinks** [comment]
The 2015-WatchInterfaces project show the old style of watch apps.  As of June 1, this approach is no longer being accepted by Apple.

**Comment by msylvester** [comment]
Thanks a lot. 

I am confused though.  We can only submit one .app.  Will this be able to produce both a watch app and an iPhone app?  Or how do we submit both?

**Comment by susanstevens** [comment]
So all watch apps have an associated iPhone app.  They'd both be part of the same project, so I'm assuming submitting them both would be fine.

**Comment by tabinks** [comment]
@msylvester Watch apps are bundled with iOS apps.  So technically its 2 apps, but they are delivered in a single bundle.
