### ISSUE TITLE
Proof of Enrollment

### ISSUE THREAD

**Issue by aaizuss** [uchicago-mobi/2016-Spring-Forum#73]
"If you apply as a student, you must provide a PDF or PNG of your current class schedule or other current proof of enrollment and your dean or principal’s contact information."

To clarify, is it enough to provide a pdf of my current class schedule and the contact information of... which dean??

to @tabinks: I literally had no time to really improve my final project from last quarter so I'm just submitting a slightly nicer version of it. I figure it's better to submit that than to submit nothing.

**Comment by tabinks** [comment]
I'm not sure which dean.

**Comment by susanstevens** [comment]
For MPCS students, I'd submit contact info for the dean of the Physical Sciences Division.  For undergrads, I'd say dean of the college.

https://physical-sciences.uchicago.edu/directories/full/dean’s-office-staff
https://college.uchicago.edu/about/office-dean-college
