### ISSUE TITLE
Filter Interface

### ISSUE THREAD

**Issue by aaizuss** [uchicago-mobi/2016-Spring-Forum#82]
Any tips on how to design the interface for actually selecting a filter for the photo? I don't know how to do the thing where you have thumbnails below the image view with a preview of what each filter looks like... would that be a scroll view with a bunch of images? Or is it a separate view controller inside of another view controller? I couldn't find any tutorials for this specifically...

**Comment by aaizuss** [comment]
Also, it seems like the most straightforward storyboard flow for taking/selecting a photo and editing it is to have some default image loaded in an image view (perhaps the most recently edited image, and some stock image for the first time the user uses the app) with the filters to choose from below it, and the options to take a photo or choose from library as buttons in the navigation bar.

**Comment by tabinks** [comment]
The most straightforward approach would be to just use buttons that have a custom image set instead of text. Each custom image button could be set from a different filter.

**Comment by aaizuss** [comment]
@tabinks and put the buttons in a scroll view in order to have a variety of filters? Or I guess it's easier to just start with the number of buttons that fits on the screen

**Comment by susanstevens** [comment]
This seems like a perfect use-case for a collection view with just one row to me.  (UICollectionView subclasses UIScrollView, but it handles the layout of cells for you, like UITableView.)

Getting a few buttons on screen is a good starting place though -- then you can worry about scrolling once the basic functionality is working.

**Comment by aaizuss** [comment]
@susanstevens Do I need to use a Collection View Controller or can I just put a  `UICollectionView` in my ViewController's view? Does it make sense to make a collection view controller as child view controller of the view controller that displays a large ImageView?

**Comment by susanstevens** [comment]
There's no real advantage to using a UICollectionViewController here. I'd just use a UICollectionView.
