### ISSUE TITLE
Tech News: Siri & Instagram

### ISSUE THREAD

**Issue by aaizuss** [uchicago-mobi/2016-Spring-Forum#86]
[What do you think of the new icon and redesign?](http://www.theverge.com/2016/5/11/11656252/instagram-redesigns-icon-app)
- Logo video: https://vimeo.com/166138104
- More info: https://medium.com/@ianspalter/designing-a-new-look-for-instagram-inspired-by-the-community-84530eb355e3#.848fwpl62

[Viv (from the creators of Siri) is apparently incredible](http://www.theverge.com/2016/5/9/11639992/viv-digital-assistant-ai-artificial-intelligence-siri)

**Comment by tabinks** [comment]
Apple, the design conscious company, is killing the designer with "the simplified black-and-white look".  It's never been easier to design an app.  White background, tab bar, black SF font, circle profile pictures, square images....done.

This makes Instagram look like every other app out there.
