### ISSUE TITLE
Google Keyboard for iPhone

### ISSUE THREAD

**Issue by aaizuss** [uchicago-mobi/2016-Spring-Forum#89]
This is very cool http://www.theverge.com/2016/5/12/11662616/google-gboard-keyboard-iphone-ios

(you can search for anything right from any app with a text box because google search is in the keyboard!) Gif search is cool, but I think dedicated gif keyboards are better for finding gifs. It's convenient to have google search and emoji search in the keyboard though!

**Comment by tabinks** [comment]
The first thing I thought of was Google would be logging my keystrokes.  If you're concerned about that read this: http://daringfireball.net/2016/05/gboard

**Comment by tabinks** [comment]
Also, I believe its pronounced "gif".

**Comment by msylvester** [comment]
jif. duh.
