### ISSUE TITLE
Google App Engine?

### ISSUE THREAD

**Issue by tabinks** [uchicago-mobi/2016-Spring-Forum#9]
If you are interested in learning about building a backend with Google App Engine as part of the class, please 👍 this.  

If there is enough interested, I'll incorporate it into lecture.

**Comment by Eric-Warehime** [comment]
:+1:

**Comment by hbennett766** [comment]
👍🏻

**Comment by aljc** [comment]
👍🏻

**Comment by aaizuss** [comment]
👍

**Comment by nickpann** [comment]
👍
