### ISSUE TITLE
Storing favorites in iCloud

### ISSUE THREAD

**Issue by aaizuss** [uchicago-mobi/2016-Spring-Forum#93]
In the slides, you suggest that one of the attributes for the Image entity should be favorite. The assignment spec says we should be able to save select a favorite photo and save it to iCloud using CloudKit. To clarify, does this mean that you can only have _one_ favorite photo? I'm confused because in your example app that uses user defaults, you have a favorites array, which suggests we can save more than one favorite. 

 Would it make sense if my favorite attribute is of type Boolean (I don't know what else it could be, since we're already saving the image data in another attribute). That way, when the user favorites an image, we just set the favorite attribute to True and save to CloudKit (and we need to find whatever the previous favorite image was, if there is one, and set its boolean to false). 

When we save in general, should the info we save to cloud kit match the entity attributes that we save with CoreData? I'm not sure how to save an id to cloud kit (do I just add another record.setValue(some number here, forKey: "id") All of the cloud kit stuff is still really fuzzy... And how should we determine the id? Start a counter from a number and just keep increasing? or generate a random number and check that it doesn't exist as an id already?

**Comment by susanstevens** [comment]
The reason to have just one favorite photo is that you'll be displaying it in the glance on the watch.  I know some people have already set up the ability to favorite multiple items on the phone app, which is fine.  I'd just pick a way to determine which of those is the photo you'll display on the glance (maybe the most recent favorite, or a randomly selected one).

Unfortunately, bool is not one of the data types supported in `CKRecord` fields, so you can't save a boolean to CloudKit.  I'd recommend saving an Int or a String instead -- just make sure you have a way of specifying one value that means false and another that means true.

Yep, you can have the info saved to CloudKit match the data saved to CoreData.  You might choose to save a bool to CoreData, though, whereas you can't do that for CloudKit.  (To anyone reading this and panicking -- using CoreData is _not_ a requirement for this assignment.)

**Comment by aaizuss** [comment]
What's the purpose of saving a thumbnail in addition to the image? Is it for loading into the collection view (if we have small collection view cells) or is it because the watch face is small so we load the thumbnail on the watch?

**Comment by tabinks** [comment]
> To clarify, does this mean that you can only have one favorite photo? I'm confused because in your example app that uses user defaults, you have a favorites array, which suggests we can save more than one favorite.

The intent was to have a single favorite image (this was supposed to make it simpler to manage for the the glance.  That example is just one example of a way to persist CloudKit data.  It is not specific for this assignment.  If you've been playing close attention that same `DataKit` framework has been used in the CoreData and CloudKit playground projects.

> When we save in general, should the info we save to cloud kit match the entity attributes that we save with CoreData?

Only save as much data locally as you need.

> I'm not sure how to save an id to cloud kit (do I just add another record.setValue(some number here, forKey: "id") All of the cloud kit stuff is still really fuzzy...  And how should we determine the id? Start a counter from a number and just keep increasing? or generate a random number and check that it doesn't exist as an id already?

`CloudKit` generates a unique identifier for every record created as part of the metadata attributes.  Use this auto generated one.

**Comment by tabinks** [comment]
> What's the purpose of saving a thumbnail in addition to the image? Is it for loading into the collection view (if we have small collection view cells) or is it because the watch face is small so we load the thumbnail on the watch?

This was just a suggestion of one way to approach the problem.  I would load thumbnails first in my collection view and then download the full size in a secondary request.  You do not need to use thumbnails for your project.

For the watch, remember, if the data is too big the operation will time out and the watch will go to sleep.  You should only try to send over a small image to the watch.  When you shrink it and how you store it is up to you.
