### ISSUE TITLE
"Stickers" On Images

### ISSUE THREAD

**Issue by aaizuss** [uchicago-mobi/2016-Spring-Forum#94]
I successfully detect faces in my images and place stickers where they're supposed to be, but I do so by adding those stickers as image views that are subviews of the main image view (the one with the photo to edit). So when I save my photo, the stickers aren't saved. Is there a way to adjust the image itself when I add the stickers (instead of just adding a subview to the image view)?

**Comment by hbennett766** [comment]
http://stackoverflow.com/questions/9257992/how-to-combine-merge-2-images-into-1

I had to mess around with my image context size, but it was relatively painless.
