### ISSUE TITLE
Images not getting saved to CloudKit - publicDB.saveRecord not called?

### ISSUE THREAD

**Issue by aaizuss** [uchicago-mobi/2016-Spring-Forum#95]
So I have all of the cloud kit stuff set up and I'm trying to debug because the images aren't actually getting saved. I'm using the add function in `CloudKitManager`, but it doesn't print anything from `publicDB.saveRecord` (there are print statements in the completion block for errors and for a successful save, but neither of those are printing). The function prints out the file URL of the image, and I have it print after setting record values (which happens before saveRecord, obviously), but I don't know if it's actually calling `saveRecord`. 

Suggestions?

**Comment by tabinks** [comment]
Are you converting to CKAsset on device first?

**Comment by aaizuss** [comment]
I'm dumb - I wasn't testing on a device
