### ISSUE TITLE
payloads too large for a watch

### ISSUE THREAD

**Issue by msylvester** [uchicago-mobi/2016-Spring-Forum#98]
Okay, sending images is okay, but has anyone been able to send an array of images via update application context?  

I cannot send more then two images to the watch at a time or i get a payload error.  Has anyone been able to send 10 images to show in the tableview?

**Comment by susanstevens** [comment]
Are you scaling the images to thumbnails?

**Comment by tabinks** [comment]
You beat me to it.  Try resizing (and compressing) the images to the exact see of theApple Watch screens:
- 38mm Apple Watch 272 x 340 pixels
- 42mm Apple Watch 312 x 390 pixels

## I would just resize to 42mm, not both.

**Comment by msylvester** [comment]
I am fairly certain, using update application context is NOT feasible for this project (at least for sending 10 images). I have tried reducing the images to sizes below what was suggested above.

It is possible that hacking could make this work. 

O/w, I think  "transfer file" is a better method of file transfer:

*_It's also possible using an appleWatch rather than a simulator could make this work.  
*_*Note, I do not have an apple watch, but, donations accepted  🤘🏻

**Comment by tabinks** [comment]
@msylvester You may be right (sending an array of images), but it didn't occur to me that you would be sending an array of 10 images over.  I would have though you would only be sending unique file ids over via application context and then requesting an image only if it needed it.

Something this this:
- A new photo is added
- Send the unique id of the recent images using application context 
- Compare to the local image ids on the watch
- If a new image is in the list, request it, save it locally and add the id to the list

Or:
- You may also elect to send the single image over directly via application context

Either way, at any given time, you should only be sending 1 image over to the watch.  The other ones should have already been sent.  If you really wanted to be a good citizen you would delete the outdated images off the watch when a new one comes in.

**Comment by msylvester** [comment]
Makes sense
